import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "gelules-ventre-plat",
    sku: "GVP-01",
    name: "Gélules Ventre Plat",
    shortDescription: "Formule botanique ciblant la sangle abdominale.",
    description: "Complément alimentaire naturel formulé à base de plantes locales sélectionnées pour accompagner votre confort digestif et soutenir une sensation de légèreté au quotidien. Aide à affiner la sangle abdominale et cible les ballonnements.",
    productType: "capsules",
    status: "published",
    categoryId: "complements",
    collectionIds: [],
    tags: ["ventre-plat", "digestion"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Gélules Ventre Plat", order: 0 }],
    price: 10000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 12,
    lowStockThreshold: 5,
    allowBackorder: false,
    variants: [],
    benefits: ["Perte de ventre ciblée", "Amélioration du transit", "Réduction des ballonnements"],
    ingredients: ["Kinkéliba sauvage", "Moringa", "Citronnelle", "Menthe"],
    usageInstructions: ["2 gélules par jour le matin avec un grand verre d'eau."],
    precautions: ["Ne pas dépasser la dose recommandée."],
    warnings: ["Consulter un médecin en cas de grossesse."],
    nutritionalInformation: null,
    weight: 0.1,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Gélules Ventre Plat | CAROANA MINCEUR", description: "Formule botanique ciblant la sangle abdominale.", keywords: [], canonicalUrl: null },
    featured: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p-kaylie",
    slug: "gelules-kaylie",
    sku: "GK-01",
    name: "Gélules Minceur Kaylie",
    shortDescription: "Cure 1 mois · Perte de 9 kg à plus · Premium.",
    description: "Cure intensive premium d'un mois conçue pour une perte de poids profonde, globale et durable. Idéal pour atteindre vos objectifs de perte de poids importants.",
    productType: "capsules",
    status: "published",
    categoryId: "complements",
    collectionIds: [],
    tags: ["minceur", "premium"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Gélules Minceur Kaylie", order: 0 }],
    price: 25000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 4,
    lowStockThreshold: 3,
    allowBackorder: false,
    variants: [],
    benefits: ["Brûle-graisses puissant", "Effet coupe-faim naturel", "Accélération du métabolisme"],
    ingredients: ["Moringa", "Garcinia", "Kinkéliba", "Plantes actives"],
    usageInstructions: ["2 gélules par jour, 30 minutes avant le petit-déjeuner."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.1,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Gélules Kaylie | CAROANA MINCEUR", description: "Cure intensive premium d'un mois", keywords: [], canonicalUrl: null },
    featured: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p-skinny",
    slug: "gelules-skinny",
    sku: "GS-01",
    name: "Gélules Minceur Skinny",
    shortDescription: "Cure 1 semaine · Perte de 1 kg à 9 kg.",
    description: "Cure express d'une semaine pour éliminer rapidement les excès et initier la perte de poids. Idéal pour un coup de fouet rapide.",
    productType: "capsules",
    status: "published",
    categoryId: "complements",
    collectionIds: [],
    tags: ["minceur", "express"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Gélules Minceur Skinny", order: 0 }],
    price: 15000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 8,
    lowStockThreshold: 3,
    allowBackorder: false,
    variants: [],
    benefits: ["Détox rapide", "Affinage express", "Relance de la digestion"],
    ingredients: ["Citronnelle", "Kinkéliba", "Plantes drainantes"],
    usageInstructions: ["2 gélules le matin avec une grande tasse d'eau tiède."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.1,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Gélules Skinny | CAROANA MINCEUR", description: "Cure express d'une semaine", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p2",
    slug: "the-detox",
    sku: "TD-01",
    name: "Thé Détox",
    shortDescription: "Kinkéliba & Citronnelle — Drainage & énergie.",
    description: "Une infusion rafraîchissante et purifiante, alliance subtile de plantes traditionnelles africaines pour purifier l'organisme en douceur.",
    productType: "tea",
    status: "published",
    categoryId: "infusions",
    collectionIds: [],
    tags: ["detox", "drainage"],
    images: [{ url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop", alt: "Thé Détox", order: 0 }],
    price: 5000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 35,
    lowStockThreshold: 5,
    allowBackorder: false,
    variants: [],
    benefits: ["Détoxification du foie et des reins", "Drainage en profondeur", "Soutien immunitaire"],
    ingredients: ["Kinkeliba", "Citronnelle", "Gingembre"],
    usageInstructions: ["1 sachet à infuser matin et soir après les repas."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.15,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Thé Détox | CAROANA MINCEUR", description: "Infusion purifiante au Kinkéliba", keywords: [], canonicalUrl: null },
    featured: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p3",
    slug: "tisane-ventre-plat",
    sku: "TVP-01",
    name: "Tisane Ventre Plat",
    shortDescription: "Formule ancestrale — Légèreté & confort digestif.",
    description: "Infusion douce favorisant le bien-être digestif et contribuant à atténuer les sensations de ballonnements de manière naturelle.",
    productType: "herbal_tea",
    status: "published",
    categoryId: "infusions",
    collectionIds: [],
    tags: ["ventre-plat", "tisane"],
    images: [{ url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop", alt: "Tisane Ventre Plat", order: 0 }],
    price: 5000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 18,
    lowStockThreshold: 5,
    allowBackorder: false,
    variants: [],
    benefits: ["Digestion légère", "Effet ventre plat au réveil", "Transit harmonieux"],
    ingredients: ["Feuilles de séné", "Menthe poivrée", "Plantes bien-être"],
    usageInstructions: ["1 tasse en infusion le soir au coucher."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.15,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Tisane Ventre Plat | CAROANA MINCEUR", description: "Infusion ventre plat", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p-tisane-m",
    slug: "tisane-minceur",
    sku: "TM-01",
    name: "Tisane Minceur",
    shortDescription: "Drainage & affinage silhouette — Plantes africaines.",
    description: "Formule active enrichie en plantes drainantes pour accélérer la perte de poids et l'élimination des graisses pendant la nuit.",
    productType: "herbal_tea",
    status: "published",
    categoryId: "infusions",
    collectionIds: [],
    tags: ["minceur", "tisane"],
    images: [{ url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop", alt: "Tisane Minceur", order: 0 }],
    price: 8000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 22,
    lowStockThreshold: 5,
    allowBackorder: false,
    variants: [],
    benefits: ["Accélération minceur", "Brûle-graisses nocturne", "Drainage lymphatique"],
    ingredients: ["Kinkéliba sauvage", "Moringa", "Feuilles de séné"],
    usageInstructions: ["1 sachet à infuser après le dîner."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.15,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Tisane Minceur | CAROANA MINCEUR", description: "Infusion minceur active", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p-produit-m",
    slug: "produit-minceur",
    sku: "PM-01",
    name: "Produit Minceur",
    shortDescription: "Formulation complémentaire minceur.",
    description: "Complément minceur polyvalent pour réguler l'appétit et optimiser les résultats de votre rituel minceur quotidien.",
    productType: "capsules",
    status: "published",
    categoryId: "complements",
    collectionIds: [],
    tags: ["supplement", "minceur"],
    images: [{ url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop", alt: "Produit Minceur", order: 0 }],
    price: 8000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 3,
    lowStockThreshold: 2,
    allowBackorder: false,
    variants: [],
    benefits: ["Régulateur d'appétit", "Sensation de satiété", "Stabilisation du poids"],
    ingredients: ["Fibres végétales", "Moringa", "Minéraux essentiels"],
    usageInstructions: ["1 dose dans un verre d'eau avant le repas."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.2,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Produit Minceur | CAROANA MINCEUR", description: "Complément coupe-faim", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p-gelules-nourrice",
    slug: "gelules-ventre-plat-nourrice",
    sku: "GVPN-01",
    name: "Gélules Ventre Plat Nourrice",
    shortDescription: "Formule post-partum et allaitement pour affiner la sangle abdominale.",
    description: "Formulation post-partum spécialement conçue pour les jeunes mamans allaitantes. Aide à retrouver un ventre plat en toute sécurité sans altérer la lactation.",
    productType: "capsules",
    status: "published",
    categoryId: "complements",
    collectionIds: [],
    tags: ["nourrice", "allaitement"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Gélules Ventre Plat Nourrice", order: 0 }],
    price: 10000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 15,
    lowStockThreshold: 4,
    allowBackorder: false,
    variants: [],
    benefits: ["Sécurisé pour l'allaitement", "Tonification de la peau du ventre", "Riche en vitamines et minéraux"],
    ingredients: ["Moringa", "Citronnelle sauvage", "Nutriments bio"],
    usageInstructions: ["2 gélules par jour le matin avec un grand verre d'eau."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.1,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Gélules Nourrice | CAROANA MINCEUR", description: "Gélules ventre plat allaitement", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p-caolin-nourrice",
    slug: "caolin-ventre-plat-nourrice",
    sku: "CVPN-01",
    name: "Caolin Ventre Plat Nourrice",
    shortDescription: "Soin traditionnel purifié pour raffermir le ventre des nouvelles mamans.",
    description: "Argile blanche purifiée combinée à des extraits de plantes traditionnelles pour raffermir la sangle abdominale post-grossesse.",
    productType: "capsules",
    status: "published",
    categoryId: "complements",
    collectionIds: [],
    tags: ["nourrice", "caolin"],
    images: [{ url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop", alt: "Caolin Ventre Plat Nourrice", order: 0 }],
    price: 5000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 19,
    lowStockThreshold: 4,
    allowBackorder: false,
    variants: [],
    benefits: ["Fermeté abdominale", "Soin de tradition maman", "Élimination des impuretés"],
    ingredients: ["Caolin purifié", "Extraits de kinkeliba", "Plantes raffermissantes"],
    usageInstructions: ["1 cuillère dans de l'eau tiède le matin, ou en masque."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.25,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Caolin Nourrice | CAROANA MINCEUR", description: "Caolin ventre plat allaitement", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "p-tisane-nourrice",
    slug: "tisane-ventre-plat-nourrice",
    sku: "TVPN-01",
    name: "Tisane Ventre Plat Nourrice",
    shortDescription: "Infusion douce favorisant le transit et le ventre plat post-grossesse.",
    description: "Infusion douce et réconfortante facilitant la digestion et le transit de la maman tout en favorisant la lactation de manière saine.",
    productType: "herbal_tea",
    status: "published",
    categoryId: "infusions",
    collectionIds: [],
    tags: ["nourrice", "tisane"],
    images: [{ url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop", alt: "Tisane Ventre Plat Nourrice", order: 0 }],
    price: 5000,
    compareAtPrice: null,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: true,
    stock: 14,
    lowStockThreshold: 4,
    allowBackorder: false,
    variants: [],
    benefits: ["Lactation soutenue", "Transit doux post-accouchement", "Légèreté et détente"],
    ingredients: ["Citronnelle sauvage", "Moringa", "Plantes douces lactation"],
    usageInstructions: ["1 sachet à infuser 5 minutes dans l'eau frémissante."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.15,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Tisane Nourrice | CAROANA MINCEUR", description: "Tisane ventre plat allaitement", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  
  // PACKS mapped as bundles (to make them renderable as product details if slug requested)
  {
    id: "pack-1",
    slug: "pack-gelules-the",
    sku: "PK-01",
    name: "Pack Gélules + Thé Détox",
    shortDescription: "Gélules Ventre Plat + Thé Détox",
    description: "Le duo idéal pour combiner l'effet brûle-graisse ciblé sur la sangle abdominale des gélules avec le drainage en profondeur du Thé Détox.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack"],
    images: [{ url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop", alt: "Pack Gélules + Thé Détox", order: 0 }],
    price: 14000,
    compareAtPrice: 15000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Perte abdominale accélérée", "Détox complète", "Économie de 1 000 F"],
    ingredients: ["Gélules Ventre Plat (10 000 F)", "Thé Détox (5 000 F)"],
    usageInstructions: ["Gélules le matin, Thé Détox après les repas."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.25,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Gélules + Thé | CAROANA MINCEUR", description: "Duo Ventre Plat et Thé Détox", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-2",
    slug: "pack-gelules-tisane",
    sku: "PK-02",
    name: "Pack Gélules + Tisane",
    shortDescription: "Gélules Ventre Plat + Tisane Ventre Plat",
    description: "Association synergique des gélules ventre plat et de la tisane au coucher pour un ventre plat garanti et une digestion parfaite.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack"],
    images: [{ url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop", alt: "Pack Gélules + Tisane", order: 0 }],
    price: 14000,
    compareAtPrice: 15000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Action double Ventre Plat", "Digestion légère", "Économie de 1 000 F"],
    ingredients: ["Gélules Ventre Plat (10 000 F)", "Tisane Ventre Plat (5 000 F)"],
    usageInstructions: ["Gélules le matin, Tisane le soir."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.25,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Gélules + Tisane | CAROANA MINCEUR", description: "Duo gélules et tisane", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-3",
    slug: "pack-the-tisane",
    sku: "PK-03",
    name: "Pack Thé + Tisane",
    shortDescription: "Thé Détox + Tisane Ventre Plat",
    description: "Le duo d'infusions parfait pour purifier le corps la journée et assurer une légèreté abdominale le soir.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack"],
    images: [{ url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop", alt: "Pack Thé + Tisane", order: 0 }],
    price: 10000,
    compareAtPrice: 10000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Hydratation active", "Détox & Confort digestif"],
    ingredients: ["Thé Détox (5 000 F)", "Tisane Ventre Plat (5 000 F)"],
    usageInstructions: ["Thé Détox la journée, Tisane le soir."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.3,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Thé + Tisane | CAROANA MINCEUR", description: "Duo d'infusions détox et ventre plat", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-complet",
    slug: "pack-complet-3-produits",
    sku: "PK-04",
    name: "Pack Complet 3 Produits",
    shortDescription: "Gélules + Thé Détox + Tisane",
    description: "La cure minceur complète pour sculpter votre corps de manière intensive. Associe gélules, thé et tisane pour des résultats visibles en 14 à 28 jours.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack", "complet"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Pack Complet 3 Produits", order: 0 }],
    price: 19000,
    compareAtPrice: 20000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Perte globale accélérée", "Ventre plat & Détox", "Économie de 1 000 F"],
    ingredients: ["Gélules Ventre Plat (10 000 F)", "Thé Détox (5 000 F)", "Tisane Ventre Plat (5 000 F)"],
    usageInstructions: ["Gélules le matin, thé après midi, tisane au coucher."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.4,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Complet 3 Produits | CAROANA MINCEUR", description: "Cure minceur complète 3 produits", keywords: [], canonicalUrl: null },
    featured: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-kaylie-the",
    slug: "pack-kaylie-the-detox",
    sku: "PK-05",
    name: "Pack Gélules Kaylie + Thé Détox",
    shortDescription: "Cure premium 1 mois + Drainage quotidien",
    description: "Le pack ultime pour celles qui recherchent une perte de poids importante et profonde. Alliez la cure premium Kaylie au drainage puissant du Thé Détox.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack", "premium"],
    images: [{ url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop", alt: "Pack Gélules Kaylie + Thé Détox", order: 0 }],
    price: 30000,
    compareAtPrice: 30000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Perte profonde 9kg+", "Brûle-graisses renforcé"],
    ingredients: ["Gélules Kaylie (25 000 F)", "Thé Détox (5 000 F)"],
    usageInstructions: ["Kaylie le matin, thé détox en infusion après midi."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.25,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Kaylie + Thé | CAROANA MINCEUR", description: "Pack Kaylie et thé détox", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-kaylie-minceur",
    slug: "pack-kaylie-tisane-minceur",
    sku: "PK-06",
    name: "Pack Gélules Kaylie + Tisane Minceur",
    shortDescription: "Transformation totale : gélules + tisane",
    description: "Cure combinée active associant les gélules Kaylie pour brûler les graisses en journée, et la Tisane Minceur pour activer le transit et drainer la nuit.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack"],
    images: [{ url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop", alt: "Pack Gélules Kaylie + Tisane Minceur", order: 0 }],
    price: 33000,
    compareAtPrice: 33000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Transformation corporelle active", "Perte ciblée et drainage"],
    ingredients: ["Gélules Kaylie (25 000 F)", "Tisane Minceur (8 000 F)"],
    usageInstructions: ["Gélules Kaylie avant le petit-déjeuner, Tisane minceur après le dîner."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.25,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Kaylie + Tisane Minceur | CAROANA MINCEUR", description: "Association Kaylie et tisane minceur", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-skinny-the",
    slug: "pack-skinny-the-detox",
    sku: "PK-07",
    name: "Pack Gélules Skinny + Thé Détox",
    shortDescription: "Résultats rapides 1 semaine + drainage",
    description: "Le starter pack express. Éliminez rapidement la rétention d'eau et perdez du poids en une semaine grâce à Skinny et au Thé Détox.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack"],
    images: [{ url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop", alt: "Pack Gélules Skinny + Thé Détox", order: 0 }],
    price: 20000,
    compareAtPrice: 20000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Détox express 1 semaine", "Élimination rapide de l'eau"],
    ingredients: ["Gélules Skinny (15 000 F)", "Thé Détox (5 000 F)"],
    usageInstructions: ["Skinny le matin, thé détox l'après-midi."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.25,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Skinny + Thé | CAROANA MINCEUR", description: "Duo express Skinny et thé", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-skinny-tisane",
    slug: "pack-skinny-tisane-minceur",
    sku: "PK-08",
    name: "Pack Gélules Skinny + Tisane Minceur",
    shortDescription: "Express 1 semaine + tisane drainante",
    description: "Combinaison express d'une semaine pour purifier votre transit intestinal et éliminer les ballonnements tenaces.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack"],
    images: [{ url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop", alt: "Pack Gélules Skinny + Tisane Minceur", order: 0 }],
    price: 23000,
    compareAtPrice: 23000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Ventre dégonflé en 7 jours", "Digestion légère & dynamique"],
    ingredients: ["Gélules Skinny (15 000 F)", "Tisane Minceur (8 000 F)"],
    usageInstructions: ["Gélules le matin, tisane après le dîner."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.25,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Skinny + Tisane | CAROANA MINCEUR", description: "Duo express Skinny et tisane", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-minceur-kaylie",
    slug: "pack-minceur-kaylie-complet",
    sku: "PK-09",
    name: "Pack Minceur Kaylie — 3 Produits",
    shortDescription: "Le pack complet transformation Kaylie",
    description: "Le nec plus ultra des cures de transformation CAROANA. Associe les puissantes gélules Kaylie, le Thé Détox et la Tisane Minceur pour une métamorphose complète en 30 jours.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack", "complet", "premium"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Pack Minceur Kaylie", order: 0 }],
    price: 38000,
    compareAtPrice: 38000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Perte globale profonde", "Triple action jour & nuit"],
    ingredients: ["Gélules Kaylie (25 000 F)", "Thé Détox (5 000 F)", "Tisane Minceur (8 000 F)"],
    usageInstructions: ["Gélules avant déjeuner, Thé l'après-midi, Tisane après dîner."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.45,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Kaylie Complet | CAROANA MINCEUR", description: "Cure complète Kaylie 3 produits", keywords: [], canonicalUrl: null },
    featured: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-minceur-skinny",
    slug: "pack-minceur-skinny-complet",
    sku: "PK-10",
    name: "Pack Minceur Skinny — 3 Produits",
    shortDescription: "Le pack complet rapide Skinny",
    description: "Cure d'attaque rapide de 7 à 10 jours pour affiner la silhouette et drainer intensément l'eau accumulée. Alliez Skinny, Thé et Tisane Minceur.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["pack", "complet"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Pack Minceur Skinny", order: 0 }],
    price: 28000,
    compareAtPrice: 28000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Détox et perte express", "Affinement immédiat sangle abdominale"],
    ingredients: ["Gélules Skinny (15 000 F)", "Thé Détox (5 000 F)", "Tisane Minceur (8 000 F)"],
    usageInstructions: ["Skinny le matin, thé dans l'après-midi, tisane au coucher."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.45,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Skinny Complet | CAROANA MINCEUR", description: "Cure complète Skinny 3 produits", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-nourrice-1",
    slug: "pack-gelules-caolin-nourrice",
    sku: "PKN-01",
    name: "Pack Gélules Nourrice + Caolin",
    shortDescription: "Duo Ventre Plat Nourrice & Maman",
    description: "Duo traditionnel et moderne pour retrouver un ventre ferme et plat après l'accouchement. Conçu pour être compatible avec l'allaitement.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["nourrice", "allaitement"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Pack Gélules Nourrice + Caolin", order: 0 }],
    price: 14000,
    compareAtPrice: 15000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Fermeté post-partum", "Sans impact sur la lactation", "Économie de 1 000 F"],
    ingredients: ["Gélules Nourrice (10 000 F)", "Caolin Nourrice (5 000 F)"],
    usageInstructions: ["Gélules le matin, Caolin en soin ou boisson tiède."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.35,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Gélules + Caolin Nourrice | CAROANA MINCEUR", description: "Duo Ventre Plat Nourrice", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-nourrice-2",
    slug: "pack-gelules-tisane-nourrice",
    sku: "PKN-02",
    name: "Pack Gélules Nourrice + Tisane",
    shortDescription: "Duo Ventre Plat & Transit Doux",
    description: "Combinaison des gélules et de la tisane douce nourrice pour un ventre plat et une digestion fluide post-grossesse sans perturber le bébé.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["nourrice", "allaitement"],
    images: [{ url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop", alt: "Pack Gélules Nourrice + Tisane", order: 0 }],
    price: 14000,
    compareAtPrice: 15000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Transit intestinal doux", "Retrait des ballonnements post-grossesse", "Économie de 1 000 F"],
    ingredients: ["Gélules Nourrice (10 000 F)", "Tisane Nourrice (5 000 F)"],
    usageInstructions: ["Gélules le matin, tisane après midi ou au coucher."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.25,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Gélules + Tisane Nourrice | CAROANA MINCEUR", description: "Duo gélules et tisane allaitement", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-nourrice-3",
    slug: "pack-caolin-tisane-nourrice",
    sku: "PKN-03",
    name: "Pack Caolin Nourrice + Tisane",
    shortDescription: "Duo Drainage & Fermeté",
    description: "Soin doux associant la tisane allaitement pour la digestion et le caolin pour la fermeté cutanée et le confort intestinal.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["nourrice", "allaitement"],
    images: [{ url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop", alt: "Pack Caolin Nourrice + Tisane", order: 0 }],
    price: 10000,
    compareAtPrice: 10000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Fermeté et drainage doux", "Compatible allaitement exclusif"],
    ingredients: ["Caolin Nourrice (5 000 F)", "Tisane Nourrice (5 000 F)"],
    usageInstructions: ["Caolin le matin, tisane en infusion l'après-midi."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.4,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Caolin + Tisane Nourrice | CAROANA MINCEUR", description: "Duo caolin et tisane allaitement", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-nourrice-4",
    slug: "pack-complet-nourrice",
    sku: "PKN-04",
    name: "Pack Complet Nourrice",
    shortDescription: "Le pack complet 3 produits Ventre Plat Nourrice",
    description: "La cure post-partum la plus complète et équilibrée. Associe gélules, tisane et caolin pour un ventre plat, ferme et tonifié en toute sérénité.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["nourrice", "complet"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Pack Complet Nourrice", order: 0 }],
    price: 20000,
    compareAtPrice: 20000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Transformation ventre plat post-grossesse", "Sûr à 100% pour maman & bébé"],
    ingredients: ["Gélules Nourrice (10 000 F)", "Caolin Nourrice (5 000 F)", "Tisane Nourrice (5 000 F)"],
    usageInstructions: ["Gélules le matin, caolin midi, tisane le soir."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.5,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Pack Complet Nourrice | CAROANA MINCEUR", description: "Cure post-partum 3 produits complète", keywords: [], canonicalUrl: null },
    featured: false,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  },
  {
    id: "pack-nourrice-kit",
    slug: "kit-ventre-plat-nourrice",
    sku: "PKN-KIT",
    name: "Kit Ventre Plat Nourrice",
    shortDescription: "Promotion spéciale : Kit Ventre Plat complet pour Maman",
    description: "L'offre phare pour les nouvelles mamans : bénéficiez de la cure complète de 3 produits Nourrice au tarif promotionnel exceptionnel de 15 000 F CFA au lieu de 20 000 F CFA.",
    productType: "bundle",
    status: "published",
    categoryId: "packs",
    collectionIds: [],
    tags: ["nourrice", "promo", "complet"],
    images: [{ url: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop", alt: "Kit Ventre Plat Nourrice Promo", order: 0 }],
    price: 15000,
    compareAtPrice: 20000,
    costPrice: null,
    currency: "XOF",
    taxable: false,
    trackInventory: false,
    stock: 99,
    lowStockThreshold: 0,
    allowBackorder: true,
    variants: [],
    benefits: ["Cure complète maman & bébé", "Économie immédiate de 5 000 F CFA"],
    ingredients: ["Gélules Nourrice (10 000 F)", "Caolin Nourrice (5 000 F)", "Tisane Nourrice (5 000 F)"],
    usageInstructions: ["Gélules le matin, caolin midi, tisane le soir."],
    precautions: [],
    warnings: [],
    nutritionalInformation: null,
    weight: 0.5,
    dimensions: { length: null, width: null, height: null },
    seo: { title: "Kit Ventre Plat Nourrice (Promo) | CAROANA MINCEUR", description: "Offre maman allaitement à 15000 F", keywords: [], canonicalUrl: null },
    featured: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: "admin",
    updatedBy: "admin"
  }
];

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: "phytotherapie" | "nutrition" | "maternite" | "bien-etre";
  tags: string[];
  imageUrl: string;
  author: string;
  readTime: string;
  publishedAt: string;
  recommendedProductSlug: string;
}

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: "post1",
    slug: "bienfaits-kinkeliba-ventre-plat",
    title: "Le Kinkéliba : Le Secret Ancestral pour un Ventre Plat",
    excerpt: "Découvrez comment cette plante sauvage d'Afrique de l'Ouest favorise le drainage, dégonfle l'estomac et purifie le foie.",
    content: `
      <p>Le <strong>Kinkéliba</strong> (<em>Combretum micranthum</em>) est un arbuste sauvage emblématique des régions sahéliennes d'Afrique de l'Ouest. Surnommé la « tisane de longue vie » au Sénégal et au Mali, il est traditionnellement consommé pour ses vertus thérapeutiques exceptionnelles.</p>
      
      <h3>Comment le Kinkéliba agit-il sur la silhouette ?</h3>
      <p>Pour les personnes cherchant à retrouver un ventre plat et à affiner leur sangle abdominale, le Kinkéliba est un allié de premier ordre :</p>
      <ul>
        <li><strong>Drainage profond :</strong> Il stimule la fonction d'élimination rénale et aide à lutter contre la rétention d'eau, responsable de la sensation de gonflement abdominal.</li>
        <li><strong>Détoxification du foie :</strong> En soutenant l'activité hépatique et biliaire, le Kinkéliba facilite la digestion des graisses et évite les lourdeurs après les repas.</li>
        <li><strong>Effet ventre plat immédiat :</strong> Grâce à ses propriétés anti-inflammatoires, il apaise le système digestif et prévient les ballonnements et fermentations intestinales.</li>
      </ul>

      <h3>Conseils de préparation pour une efficacité maximale</h3>
      <p>Pour en retirer tous les bénéfices, nous vous conseillons de faire infuser les feuilles séchées dans de l'eau frémissante pendant 10 à 15 minutes. Consommez de préférence une tasse le matin à jeun pour réactiver les fonctions d'élimination de l'organisme, et une autre tasse après le repas du midi.</p>
      
      <p>Notre formule exclusive de <em>Thé Détox Premium</em> associe le Kinkéliba sauvage à de la citronnelle fraîche pour optimiser le goût et multiplier les bienfaits sur le transit digestif.</p>
    `,
    category: "phytotherapie",
    tags: ["Kinkéliba", "Drainage", "Ventre Plat", "Détox"],
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop",
    author: "Dr. Aminata Touré, Nutritionniste",
    readTime: "4 min",
    publishedAt: "18 Juin 2026",
    recommendedProductSlug: "the-detox"
  },
  {
    id: "post2",
    slug: "post-partum-ventre-plat-allaitement",
    title: "Maman Allaitante : Comment retrouver un Ventre Plat en Douceur",
    excerpt: "Retrouver sa silhouette après l'accouchement tout en préservant la qualité de son lait maternel. Conseils et plantes recommandées.",
    content: `
      <p>La période du post-partum est une phase de transition délicate pour le corps d'une nouvelle maman. Vouloir retrouver sa sangle abdominale d'avant-grossesse est tout à fait naturel, mais l'allaitement impose des précautions très strictes concernant la consommation de compléments minceur.</p>

      <h3>La sécurité de bébé avant tout</h3>
      <p>De nombreux brûleurs de graisses et draineurs intensifs contiennent des substances stimulantes (caféine, théine en excès, ou plantes laxatives) qui passent directement dans le lait maternel. Ces actifs peuvent provoquer de l'irritabilité, de l'insomnie ou des coliques chez le nourrisson. Il est donc crucial d'exclure les cures minceur standards.</p>

      <h3>Les plantes amies de la maman nourrice</h3>
      <p>Heureusement, la pharmacopée traditionnelle africaine recèle de plantes parfaitement adaptées et sûres pour les mamans allaitantes :</p>
      <ul>
        <li><strong>Le Fenouil :</strong> En plus de lutter contre les ballonnements et les gaz de la maman, il stimule naturellement la lactation (effet galactogène) et apaise les coliques du bébé via le lait.</li>
        <li><strong>La Citronnelle douce :</strong> Elle favorise une bonne digestion globale et aide à désenfler en douceur sans exciter bébé.</li>
        <li><strong>Le Caolin Purifié traditionnel :</strong> Appliqué en masque sur le ventre ou consommé sous sa forme ultra-purifiée, il est historiquement utilisé pour raffermir les tissus relâchés après l'accouchement.</li>
      </ul>

      <p>C'est pour répondre à cette double exigence de sécurité et d'efficacité que nous avons conçu la gamme <strong>Caroana Nourrice</strong>, certifiée sans aucun stimulant nocif pour le nourrisson.</p>
    `,
    category: "maternite",
    tags: ["Allaitement", "Post-partum", "Maman", "Nourrice"],
    imageUrl: "https://images.unsplash.com/photo-1611070973770-b1a672610042?q=80&w=600&auto=format&fit=crop",
    author: "Fatoumata Sylla, Sage-femme",
    readTime: "5 min",
    publishedAt: "15 Juin 2026",
    recommendedProductSlug: "kit-ventre-plat-nourrice"
  },
  {
    id: "post3",
    slug: "3-regles-nutrition-perte-de-poids",
    title: "Les 3 Règles d'Or de la Nutrition pour Accompagner votre Cure",
    excerpt: "Pour maximiser l'efficacité de vos gélules Minceur, adaptez votre assiette avec ces principes simples et durables.",
    content: `
      <p>Prendre des compléments alimentaires ou boire des tisanes minceur est une excellente méthode pour activer le déstockage des graisses et drainer l'organisme. Cependant, pour obtenir des résultats durables et éviter l'effet yoyo, l'assiette joue un rôle clé.</p>

      <h3>1. Maîtrisez l'index glycémique (IG) de vos repas</h3>
      <p>Lorsque vous consommez des glucides raffinés (pain blanc, riz blanc cassé, sucre blanc, sodas), votre taux de sucre sanguin grimpe en flèche. Cela provoque un pic d'insuline, l'hormone responsable du stockage des graisses, notamment sur l'abdomen. Privilégiez les céréales complètes, le manioc, l'igname ou la patate douce qui fournissent une énergie diffuse sans stocker.</p>

      <h3>2. Ne négligez pas les protéines de qualité</h3>
      <p>Les protéines ont un fort pouvoir rassasiant et nécessitent de l'énergie pour être digérées (effet thermique des aliments). Elles permettent également de préserver la masse musculaire pendant que vous perdez de la graisse. Misez sur le poisson frais, le poulet sans peau, les œufs et les légumineuses locales comme le niébé.</p>

      <h3>3. L'importance cruciale de l'eau</h3>
      <p>Boire de l'eau est indispensable pour éliminer les déchets cellulaires libérés par la combustion des graisses. Sans une hydratation abondante (au moins 2 litres par jour), le corps retient les toxines, ce qui ralentit la perte de poids. Utilisez nos tisanes drainantes pour rendre l'eau active et optimiser l'élimination.</p>
    `,
    category: "nutrition",
    tags: ["Nutrition", "Régime", "Index Glycémique", "Protéines"],
    imageUrl: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop",
    author: "Serge Kassi, Coach Sportif & Diététicien",
    readTime: "3 min",
    publishedAt: "10 Juin 2026",
    recommendedProductSlug: "gelules-kaylie"
  }
];

